# Generated by Django 3.1.2 on 2020-10-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('X', models.FloatField(help_text='Longtitude')),
                ('Y', models.FloatField(help_text='Latitude')),
                ('unique_id', models.CharField(help_text='Squirrel ID', max_length=200, primary_key=True, serialize=False)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift', max_length=100, null=True)),
                ('date', models.DateField(help_text='Date')),
                ('age', models.CharField(choices=[('Juvenile', 'Juvenile'), ('Adult', 'Adult')], help_text='Age', max_length=100, null=True)),
            ],
        ),
    ]
